### ISSUE TITLE
its not working in nestedscrollview

### ISSUE THREAD

**Issue by hardikpatel2301** [wflfei/auto-loop-viewpager#1]
i tried to use in nestedscrollview but not displaying

<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    tools:context=".ui.MainActivity">

```
<android.support.design.widget.AppBarLayout
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:theme="@style/AppTheme.AppBarOverlay">

    <FrameLayout
        android:id="@+id/toolbar_container"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <include layout="@layout/include_toolbar" />

    </FrameLayout>

</android.support.design.widget.AppBarLayout>

<android.support.v4.widget.NestedScrollView
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fillViewport="true"
    android:theme="@style/ThemeOverlay.AppCompat.Light"
    app:layout_behavior="@string/appbar_scrolling_view_behavior">

<LinearLayout
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <com.atlassoftweb.praisecart.viewPager.AutoLoopPager
        android:id="@+id/autoPager"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />

    <android.support.v7.widget.RecyclerView
        android:id="@+id/my_recycler_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scrollbars="none" />
</LinearLayout>

</android.support.v4.widget.NestedScrollView>
```

</android.support.design.widget.CoordinatorLayout>

**Comment by wflfei** [comment]
Many thanks for your feedback. I have fixed this just now.
- When layout this within a NestedScrollView, It seems to be measured with mode: UNSPECFIED. And that's what I have not considered.

**Comment by hardikpatel2301** [comment]
Thanks for update.Did you tried with NestedScrollView? Now pager is display but behind toolbar.Pager topbar hides behind toolbar.

**Comment by wflfei** [comment]
I have tried with ViewPager in support-v4, but it happened too. Maybe we can write the NestedScroll View ourselves
